# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('entry_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('jp_1', models.CharField(max_length=255)),
                ('jp_2', models.CharField(max_length=255)),
                ('zh_1', models.CharField(max_length=255)),
                ('fr_1', models.CharField(max_length=255)),
                ('fr_2', models.CharField(max_length=255)),
                ('en_1', models.CharField(max_length=255)),
                ('lesson', models.IntegerField()),
                ('thematic', models.IntegerField()),
                ('lv', models.IntegerField()),
            ],
        ),
    ]
