# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-30 22:01
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryBackUpEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.IntegerField(db_column='backup_id')),
                ('jp_1', models.CharField(blank=True, max_length=255, null=True)),
                ('jp_2', models.CharField(blank=True, max_length=255, null=True)),
                ('zh_1', models.CharField(blank=True, max_length=255, null=True)),
                ('fr_1', models.CharField(blank=True, max_length=255, null=True)),
                ('fr_2', models.CharField(blank=True, max_length=255, null=True)),
                ('en_1', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson', models.IntegerField(null=True)),
                ('thematic', models.IntegerField(
                    choices=[(-1, 'Non Defined'), (0, 'Consummer Society'), (1, 'Economy'), (2, 'Science'),
                             (3, 'Quantity'), (4, 'Body Beauty'), (5, 'Shops'), (6, 'Animals'), (7, 'Food'),
                             (8, 'Education'), (9, 'Computer'), (10, 'Justice'), (11, 'Politique'),
                             (12, 'Programmation'), (13, 'Nature'), (14, 'Body'), (15, 'Weather'), (16, 'Clothes'),
                             (17, 'Colors'), (18, 'Numbers'), (19, 'Time'), (20, 'Family'), (21, 'Professional'),
                             (22, 'Society'), (23, 'Culture'), (24, 'Medical'), (25, 'Trip'), (26, 'Leisure'),
                             (27, 'Opinion')], null=True)),
                ('lv', models.IntegerField(
                    choices=[(0, 'Non Defined'), (1, 'Level1'), (2, 'Level2'), (3, 'Level3'), (4, 'Level4'),
                             (5, 'Level5(easiest)')], null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('entry_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('jp_1', models.CharField(blank=True, max_length=255, null=True)),
                ('jp_2', models.CharField(blank=True, max_length=255, null=True)),
                ('zh_1', models.CharField(blank=True, max_length=255, null=True)),
                ('fr_1', models.CharField(blank=True, max_length=255, null=True)),
                ('fr_2', models.CharField(blank=True, max_length=255, null=True)),
                ('en_1', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson', models.IntegerField(null=True)),
                ('thematic', models.IntegerField(
                    choices=[(-1, 'Non Defined'), (0, 'Consummer Society'), (1, 'Economy'), (2, 'Science'),
                             (3, 'Quantity'), (4, 'Body Beauty'), (5, 'Shops'), (6, 'Animals'), (7, 'Food'),
                             (8, 'Education'), (9, 'Computer'), (10, 'Justice'), (11, 'Politique'),
                             (12, 'Programmation'), (13, 'Nature'), (14, 'Body'), (15, 'Weather'), (16, 'Clothes'),
                             (17, 'Colors'), (18, 'Numbers'), (19, 'Time'), (20, 'Family'), (21, 'Professional'),
                             (22, 'Society'), (23, 'Culture'), (24, 'Medical'), (25, 'Trip'), (26, 'Leisure'),
                             (27, 'Opinion')], null=True)),
                ('lv', models.IntegerField(
                    choices=[(0, 'Non Defined'), (1, 'Level1'), (2, 'Level2'), (3, 'Level3'), (4, 'Level4'),
                             (5, 'Level5(easiest)')], null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
