# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db_editor', '0002_auto_20170814_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='lv',
            field=models.IntegerField(
                choices=[(0, 'Non Defined'), (1, 'Level1'), (2, 'Level2'), (3, 'Level3'), (4, 'Level4'),
                         (5, 'Level5(easiest)')], null=True),
        ),
    ]
