# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-20 05:34
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db_editor', '0005_auto_20170815_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
